default:
  selector: textarea.tinymce
  plugins:
    - link
    - image
    - lists
    - table
    #- autoresize
    - contextmenu
    - fullscreen
    - paste
    - searchreplace
    - template
    - textcolor
    - code

  image_advtab: true # For extended image functionality
  file_browser_callback : elFinderBrowser
  contextmenu: link image inserttable | cell row column deletetable
  templates: "/assets/tinymce/customized/template.json"
  toolbar: undo redo | styleselect | bold italic |  alignleft aligncenter alignright alignjustify |  bullist numlist outdent indent | link image hr code fullscreen | table template forecolor backcolor  
  convert_urls: false
  height: 560

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | link image | undo redo | table
  plugins:
    - table