default:
  plugins:
    - image
    - link
  file_browser_callback : elFinderBrowser

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | link image | undo redo | table
  plugins:
    - table