# default:
#   selector: textarea.tinymce
#   plugins:
#     - link
#     - image
#     - lists
#     - table
#     #- autoresize
#     - contextmenu
#     - fullscreen
#     - paste
#     - searchreplace
#     - template
#     - textcolor
#     - code

#   entity_encoding: "raw"
#   image_advtab: true # For extended image functionality
#   file_browser_callback: elFinderBrowser
#   contextmenu: link image inserttable | cell row column deletetable
#   templates: "/assets/tinymce/customized/template.json"
#   toolbar: undo redo | styleselect forecolor backcolor | bold italic |  alignleft aligncenter alignright alignjustify |  bullist numlist outdent indent | link image template table hr | code fullscreen 
#   convert_urls: false
#   height: 560

# alternate:
#   selector: textarea.table-editor
#   toolbar: styleselect | bold italic | link image | undo redo | table
#   plugins:
#     - table

default:
  plugins:
    - image
    - link
    - lists
    - table
    #- autoresize
    - contextmenu
    - fullscreen
    - paste
    - searchreplace
    - template
    - textcolor
    - code
    # - importcss

  entity_encoding: "raw"
  image_advtab: true # For extended image functionality
  file_browser_callback: elFinderBrowser
  contextmenu: link image inserttable | cell row column deletetable
  templates: "/assets/tinymce/customized/template.json"


  menubar: true
  menubar: open edit insert view format table# tools

  #toolbar: undo redo | styleselect forecolor backcolor | bold italic | alignleft aligncenter alignright alignjustify |  bullist numlist outdent indent | link image template table hr | code fullscreen 
  toolbar: undo redo | styleselect removeformat forecolor backcolor | bold italic | alignleft aligncenter alignright alignjustify |  bullist numlist outdent indent | link image template table hr | code fullscreen 
  convert_urls: false
  # relative_urls: false

  height: 480

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | link image | undo redo | table
  plugins:
    - table